all: part1 part2

part1:
	as -o lab4part1.o lab4part1.s
	gcc -o lab4part1 lab4part1.o

part2:
	as -o lab4part2.o lab4part2.s
	gcc -o lab4part2 lab4part2.o
	
clean:
	rm lab4part1.o
	rm lab4part1
	rm lab4part2.o
	rm lab4part2