all: part1 part2 part3

part1:
	gcc -o lab2part1 lab2part1.c -lwiringPi

part2:
	gcc -o lab2part2 lab2part2.c -lwiringPi

part3:
	gcc -o lab2part3 lab2part3.c -lwiringPi

clean:
	rm lab2part1
	rm lab2part2
	rm lab2part3
